#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Resume
url: 'http://www.lilanga.me'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/resume' 

description: My Resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: dark # ceramic, dark
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics:

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
